Add PUBLIC_KEY_URL option
linuxserver/docker-openssh-server pull request #41
Opened 2021-04-28 21:36 UTC by xezpeleta

The public key will be downloaded from the environment variable PUBLIC_KEY_URL

[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

 - [x] I have read the [contributing](https://github.com/linuxserver/docker-openssh-server/blob/master/.github/CONTRIBUTING.md) guideline and understand that I have made the correct modifications

------------------------------

## Description:
The following PR adds the option to download the public key from a URL, using the environment variable "PUBLIC_KEY_URL"

## Benefits of this PR and context:
For instance you could add the following environment variable: `PUBLIC_KEY_URL=https://github.com/username.keys` so you don't need to copy-paste the keys or copy the files.

## How Has This Been Tested?
I've tested with the example docker-compose.yml

2021-04-29 15:59 UTC, aptalca commented on root/etc/cont-init.d/50-config
> +    PUBLIC_KEY_DOWNLOADED=$(curl -s $PUBLIC_KEY_URL)
Missing `&& \` at the end

2021-04-29 16:00 UTC, aptalca requested changes
Logic looks good except for the missing `&& \`

Please add the var listing as optional to readme-vars.yml, and add a changelog entry

2021-05-11 20:14 UTC, xezpeleta commented
Hi! Is this resolved? Or is there any other change missing?

Thanks

2021-05-11 20:48 UTC, tobbenb commented
Read aptalcas comment again and you'll see what you need to add.

2021-05-22 14:33 UTC, Roxedus commented
To echo aptalca; Please add the var listing as optional to readme-vars.yml, and add a changelog entry

2021-11-21 17:13 UTC, aptalca approved these changes

2021-11-21 17:13 UTC, merged